import type { Project } from "@/content/types";

// Newest first. Entries marked `pending: true` have a confirmed tech stack
// (pulled straight from GitHub) but no confirmed write-up yet — ask Rômulo
// directly, or fill in `summary`/`notes` once you have the details.
export const projects: Project[] = [
  {
    slug: "dashboard-sample",
    title: "Dashboard Sample",
    role: "Next.js · TypeScript",
    summary: "Description pending — ping me and I'll fill in the details.",
    pending: true,
    layers: ["interface"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/dashboard-sample",
    demoUrl: "https://dashboard-sample-pearl.vercel.app",
    year: 2026,
  },
  {
    slug: "smart-lab",
    title: "Smart Lab",
    role: "React Native (Expo) · TypeScript",
    summary: "Description pending — ping me and I'll fill in the details.",
    pending: true,
    layers: ["interface", "application"],
    tech: ["reactnative", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/smart-lab",
    notes: [
      "Paired with a separate backend service (smart-lab-backend) in the same GitHub account.",
    ],
    year: 2025,
  },
  {
    slug: "ecommerce-challenge",
    title: "E-commerce Challenge",
    role: "Next.js · TypeScript",
    summary:
      "A single e-commerce product screen (a T-shirt page), built as part of a take-home challenge for a company I was applying to.",
    layers: ["interface"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/ecommerce-challenge",
    demoUrl: "https://ecommerce-challenge-eight.vercel.app",
    year: 2025,
  },
  {
    slug: "financial-manager",
    title: "Financial Manager",
    role: "Next.js · TypeScript",
    summary: "Description pending — ping me and I'll fill in the details.",
    pending: true,
    layers: ["interface", "application"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/financial-manager",
    year: 2024,
  },
  {
    slug: "codepix",
    title: "CodePix",
    role: "Go",
    summary: "Description pending — ping me and I'll fill in the details.",
    pending: true,
    layers: ["application", "data"],
    tech: ["go"],
    repoUrl: "https://github.com/valentimcanejo/codepix",
    year: 2024,
  },
  {
    slug: "login-api",
    title: "Login API",
    role: "Next.js · TypeScript",
    summary: "Description pending — ping me and I'll fill in the details.",
    pending: true,
    layers: ["interface", "application"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/login-api",
    demoUrl: "https://login-api-bice.vercel.app",
    year: 2023,
  },
  {
    slug: "nest-app",
    title: "Nest App",
    role: "TypeScript",
    summary: "Description pending — ping me and I'll fill in the details.",
    pending: true,
    layers: ["application"],
    tech: ["typescript"],
    repoUrl: "https://github.com/valentimcanejo/nest-app",
    year: 2023,
  },
  {
    slug: "desafio-frexco",
    title: "Desafio Frexco",
    role: "React · TypeScript · Material UI",
    summary:
      "A shopping simulation built for a technical challenge, consuming the Fruityvice public API for product data.",
    layers: ["interface", "application"],
    tech: ["react", "typescript", "mui"],
    repoUrl: "https://github.com/valentimcanejo/desafio-frexco",
    year: 2022,
  },
  {
    slug: "eth-wallet",
    title: "ETH Wallet",
    role: "React · TypeScript · Ethereum",
    summary:
      "An Ethereum transfer interface built in React and TypeScript for a technical challenge.",
    layers: ["interface", "application", "data"],
    tech: ["react", "typescript", "ethereum", "mui"],
    repoUrl: "https://github.com/valentimcanejo/desafio-dexkit",
    year: 2021,
  },
];
