import type { Project } from "@/content/types";

// Mais recentes primeiro. Itens com `pending: true` têm stack confirmada
// (direto do GitHub) mas ainda sem descrição confirmada — pergunte ao
// Rômulo, ou complete `summary`/`notes` quando tiver os detalhes.
export const projects: Project[] = [
  {
    slug: "dashboard-sample",
    title: "Dashboard Sample",
    role: "Next.js · TypeScript",
    summary: "Descrição pendente — me chame que eu conto os detalhes.",
    pending: true,
    layers: ["interface"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/dashboard-sample",
    demoUrl: "https://dashboard-sample-pearl.vercel.app",
    year: 2026,
  },
  {
    slug: "smart-lab",
    title: "Smart Lab",
    role: "React Native (Expo) · TypeScript",
    summary: "Descrição pendente — me chame que eu conto os detalhes.",
    pending: true,
    layers: ["interface", "application"],
    tech: ["reactnative", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/smart-lab",
    notes: [
      "Acompanhado de um serviço de backend separado (smart-lab-backend) na mesma conta do GitHub.",
    ],
    year: 2025,
  },
  {
    slug: "ecommerce-challenge",
    title: "E-commerce Challenge",
    role: "Next.js · TypeScript",
    summary:
      "Uma tela de produto de e-commerce (uma página de camiseta), feita como parte de um desafio técnico para uma empresa em que eu estava me candidatando.",
    layers: ["interface"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/ecommerce-challenge",
    demoUrl: "https://ecommerce-challenge-eight.vercel.app",
    year: 2025,
  },
  {
    slug: "financial-manager",
    title: "Financial Manager",
    role: "Next.js · TypeScript",
    summary: "Descrição pendente — me chame que eu conto os detalhes.",
    pending: true,
    layers: ["interface", "application"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/financial-manager",
    year: 2024,
  },
  {
    slug: "codepix",
    title: "CodePix",
    role: "Go",
    summary: "Descrição pendente — me chame que eu conto os detalhes.",
    pending: true,
    layers: ["application", "data"],
    tech: ["go"],
    repoUrl: "https://github.com/valentimcanejo/codepix",
    year: 2024,
  },
  {
    slug: "login-api",
    title: "Login API",
    role: "Next.js · TypeScript",
    summary: "Descrição pendente — me chame que eu conto os detalhes.",
    pending: true,
    layers: ["interface", "application"],
    tech: ["nextjs", "typescript"],
    repoUrl: "https://github.com/valentimcanejo/login-api",
    demoUrl: "https://login-api-bice.vercel.app",
    year: 2023,
  },
  {
    slug: "nest-app",
    title: "Nest App",
    role: "TypeScript",
    summary: "Descrição pendente — me chame que eu conto os detalhes.",
    pending: true,
    layers: ["application"],
    tech: ["typescript"],
    repoUrl: "https://github.com/valentimcanejo/nest-app",
    year: 2023,
  },
  {
    slug: "desafio-frexco",
    title: "Desafio Frexco",
    role: "React · TypeScript · Material UI",
    summary:
      "Uma simulação de loja feita para um desafio técnico, consumindo a API pública da Fruityvice para dados de produtos.",
    layers: ["interface", "application"],
    tech: ["react", "typescript", "mui"],
    repoUrl: "https://github.com/valentimcanejo/desafio-frexco",
    year: 2022,
  },
  {
    slug: "eth-wallet",
    title: "ETH Wallet",
    role: "React · TypeScript · Ethereum",
    summary:
      "Uma interface de transferência de Ethereum feita em React e TypeScript para um desafio técnico.",
    layers: ["interface", "application", "data"],
    tech: ["react", "typescript", "ethereum", "mui"],
    repoUrl: "https://github.com/valentimcanejo/desafio-dexkit",
    year: 2021,
  },
];
